server.port=5454

spring.application.name=Ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_bazaar
spring.datasource.username=postgres
spring.datasource.passwor

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manjith2244@gmail.com
spring.mail.password=your password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



razorpay.api.key=your razorpay key
razorpay.api.secret=your razorpay secret key

stripe.api.key=your stripe key

spring.devtools.livereload.enabled=true

#ai
gemini.api.key=your gemini api key
